package chess;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PawnTest {
    Pawn pawn = new Pawn(new int[] {1, 1}, true);

    @Test
    void validateMovement() {
        assertFalse(pawn.validateMovement(new int[]{0, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{0, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 1}, null));
        assertTrue(pawn.validateMovement(new int[]{1, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{1, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{2, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{3, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{4, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{5, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{6, 7}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 0}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 1}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 2}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 3}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 4}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 5}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 6}, null));
        assertFalse(pawn.validateMovement(new int[]{7, 7}, null));

        assertFalse(pawn.validateMovement(new int[]{0, 0}, new Pawn(new int[]{0, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{0, 1}, new Pawn(new int[]{0, 1}, true)));
        assertTrue(pawn.validateMovement(new int[]{0, 2}, new Pawn(new int[]{0, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{0, 3}, new Pawn(new int[]{0, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{0, 4}, new Pawn(new int[]{0, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{0, 5}, new Pawn(new int[]{0, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{0, 6}, new Pawn(new int[]{0, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{0, 7}, new Pawn(new int[]{0, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 0}, new Pawn(new int[]{1, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 1}, new Pawn(new int[]{1, 1}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 2}, new Pawn(new int[]{1, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 3}, new Pawn(new int[]{1, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 4}, new Pawn(new int[]{1, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 5}, new Pawn(new int[]{1, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 6}, new Pawn(new int[]{1, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{1, 7}, new Pawn(new int[]{1, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 0}, new Pawn(new int[]{2, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 1}, new Pawn(new int[]{2, 1}, true)));
        assertTrue(pawn.validateMovement(new int[]{2, 2}, new Pawn(new int[]{2, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 3}, new Pawn(new int[]{2, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 4}, new Pawn(new int[]{2, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 5}, new Pawn(new int[]{2, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 6}, new Pawn(new int[]{2, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{2, 7}, new Pawn(new int[]{2, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 0}, new Pawn(new int[]{3, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 1}, new Pawn(new int[]{3, 1}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 2}, new Pawn(new int[]{3, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 3}, new Pawn(new int[]{3, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 4}, new Pawn(new int[]{3, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 5}, new Pawn(new int[]{3, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 6}, new Pawn(new int[]{3, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{3, 7}, new Pawn(new int[]{3, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 0}, new Pawn(new int[]{4, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 1}, new Pawn(new int[]{4, 1}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 2}, new Pawn(new int[]{4, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 3}, new Pawn(new int[]{4, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 4}, new Pawn(new int[]{4, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 5}, new Pawn(new int[]{4, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 6}, new Pawn(new int[]{4, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{4, 7}, new Pawn(new int[]{4, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 0}, new Pawn(new int[]{5, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 1}, new Pawn(new int[]{5, 1}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 2}, new Pawn(new int[]{5, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 3}, new Pawn(new int[]{5, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 4}, new Pawn(new int[]{5, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 5}, new Pawn(new int[]{5, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 6}, new Pawn(new int[]{5, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{5, 7}, new Pawn(new int[]{5, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 0}, new Pawn(new int[]{6, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 1}, new Pawn(new int[]{6, 1}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 2}, new Pawn(new int[]{6, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 3}, new Pawn(new int[]{6, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 4}, new Pawn(new int[]{6, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 5}, new Pawn(new int[]{6, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 6}, new Pawn(new int[]{6, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{6, 7}, new Pawn(new int[]{6, 7}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 0}, new Pawn(new int[]{7, 0}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 1}, new Pawn(new int[]{7, 1}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 2}, new Pawn(new int[]{7, 2}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 3}, new Pawn(new int[]{7, 3}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 4}, new Pawn(new int[]{7, 4}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 5}, new Pawn(new int[]{7, 5}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 6}, new Pawn(new int[]{7, 6}, true)));
        assertFalse(pawn.validateMovement(new int[]{7, 7}, new Pawn(new int[]{7, 7}, true)));
    }
}